name: gym_bar
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #firebase packs.
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_auth_web: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.0

  #patterns and services.
  http_parser: ^4.0.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.2
  cached_network_image: 3.0.0-nullsafety

  #ui packs.
  #todo: replace soon.
  search_widget: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/clients.jpeg
    - assets/images/employers.jpg
    - assets/images/branches.jpg
    - assets/images/products.jpg
    - assets/images/logo.jpg
    - assets/images/add.jpg
    - assets/images/banana.jpg
    - assets/images/myprofile.jpg
    - assets/images/deposit.png
    - assets/images/withdraw.png
    - ios/Runner.xcworkspace/xcshareddata/
    - ios/Runner/Assets.xcassets/
    - ios/Runner/Base.lproj/
    - ios/Runner/
    - ios/Runner.xcworkspace/
    - ios/
    - ios/Runner/Assets.xcassets/LaunchImage.imageset/
    - ios/Runner.xcodeproj/
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/
    - ios/build/XCBuildData/
    - ios/build/
    - ios/Runner.xcodeproj/xcshareddata/
    - ios/Runner.xcodeproj/project.xcworkspace/
    - ios/Runner.xcodeproj/xcshareddata/xcschemes/
    - ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/
    - ios/Flutter/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
